### ISSUE TITLE
Client sends invalid request if UriInterface contains relative path

### ISSUE THREAD

**Issue by remorhaz** [amphp/http-client#268]
Seems that client fails to detect relative paths in `UriInterface`.
PSR-7 [tells](https://www.php-fig.org/psr/psr-7/):

> The path can either be empty or absolute (starting with a slash) or rootless (not starting with a slash). Implementations MUST support all three syntaxes.

The code that builds the raw HTTP 1 header [is here](https://github.com/amphp/http-client/blob/cb88d3b72ec5a474694e347fa4c5625ed42ca850/src/Connection/Http1Connection.php#L695). It tries to replace empty string with a slash (in fact, a bit incorrectly because it implicitly casts string to bool and this will match not only an empty string but also `"0"`, for example), but it will leave relative path (`"foo/bar"`, for example) untouched, silently putting it into start line of HTTP request as is. This makes the request broken - for example, `amphp/http-server` [interprets](https://github.com/amphp/http-server/blob/10b29b19e3900a5ebe251a139d6c04834cc25e9c/src/Driver/Http1Driver.php#L451) such a request as an `authority-form` and fails to accept it.

So, `UriInterface` doesn't protect us from relative path, but if user omits the slash - the code breaks, and the bug can be detected only by integration tests (thanks to the Universe, I had them). I would suggest to make the client ensure the slash in the beginning of non-empty paths. If, for some reason, it's undesirable - client should at least fail before sending the request.

**Comment by kelunik** [comment]
It should definitely check that the path is absolute, yes. Mind sending a PR?

The `?:` is correct as long as all paths are absolute, because it won't evaluate to false for `/0`.

**Comment by remorhaz** [comment]
Sure, I'll make a PR soon.

**Comment by kelunik** [comment]
I think throwing an exception makes sense, because we can't resolve relative paths without a base URL.

We already do the same for invalid schemes and empty hosts here:

https://github.com/amphp/http-client/blob/16ed360ffb51641b36b0ef26ba2efadc18f336a7/src/Connection/DefaultConnectionFactory.php#L52-L64

**Comment by kelunik** [comment]
Closed via #269.

**Comment by kelunik** [comment]
I've switched to Laminas instead of the mock and removed the whole URI from the exception message, because it's confusing, because the string representation always shows as absolute path. I've also centralized the logic.

https://github.com/amphp/http-client/commit/3ae1c6c8d016e6b25bd97f486a0c19e01395843b
